import { describe, expect, it } from 'vitest';
import { ContractError, decodeBootstrap, decodeRun, decodeRuns } from './contract';
import { fictionalBootstrapV2, fictionalRun, fictionalRunV2 } from './fixtures';
import backendFictionalRun from './backend-run.fixture.json';

describe('public signal supplemental contract 2.0.0', () => {
  it('decodes the public fictional artifact generated by the backend', () => {
    expect(decodeRun(backendFictionalRun)).toEqual(backendFictionalRun);
  });
  it('accepts saved context and structured evidence, including mixed-version history', () => {
    expect(decodeBootstrap(fictionalBootstrapV2)).toEqual(fictionalBootstrapV2);
    expect(decodeRun(fictionalRunV2)).toEqual(fictionalRunV2);
    expect(decodeRuns({ schemaVersion: '2.0.0', runs: [fictionalRun, fictionalRunV2] })).toHaveLength(2);
  });
  it('keeps supplemental versions explicit and rejects missing context, unknown and private fields', () => {
    expect(() => decodeRun({ ...fictionalRunV2, schemaVersion: '1.0.0' })).toThrow(ContractError);
    expect(() => decodeRun({ ...fictionalRunV2, schemaVersion: '2.1.0' })).toThrow(ContractError);
    expect(() => decodeRun({ ...fictionalRunV2, input: { watch: fictionalRunV2.input.watch } })).toThrow(ContractError);
    expect(() => decodeRun({ ...fictionalRunV2, input: { ...fictionalRunV2.input, storageLocation: 'private' } })).toThrow(ContractError);
  });
  it('rejects context identity, coverage and evidence mismatches', () => {
    for (const change of [
      (run: typeof fictionalRunV2) => { run.input.context.entity.id = 'another'; },
      (run: typeof fictionalRunV2) => { run.input.context.beforeDataset.id = 'another'; },
      (run: typeof fictionalRunV2) => { run.input.context.afterDataset.coverage = 'another'; },
      (run: typeof fictionalRunV2) => { run.signal!.recordFacts[0].recordId = 'unknown'; },
      (run: typeof fictionalRunV2) => { run.signal!.relationships[0].supportingEvidenceIds = ['source-1']; },
      (run: typeof fictionalRunV2) => { run.signal!.relationships[0].relation = 'direct'; run.signal!.relationships[0].supportingEvidenceIds = []; },
    ]) {
      const run = structuredClone(fictionalRunV2); change(run);
      expect(() => decodeRun(run)).toThrow(ContractError);
    }
  });
  it('accepts fictional namespaced source identifiers without weakening routed identifiers', () => {
    const run = structuredClone(fictionalRunV2);
    const id = `entity:${'a'.repeat(64)}`;
    run.input.context.entity.id = id; run.input.watch.entityId = id; run.signal!.recordFacts[0].applicant.entityId = id;
    run.input.context.category.id = 'H1:example.1'; run.input.watch.categoryId = 'H1:example.1';
    expect(decodeRun(run)).toEqual(run);
    expect(() => decodeRun({ ...run, id: 'run:example' })).toThrow(ContractError);
  });
  it('rejects unobserved quotes, impossible excerpt counts and unsafe discovery links', () => {
    const run = structuredClone(fictionalRunV2);
    run.signal!.sources[0].modelVisibleChars = 2; run.signal!.sources[0].truncated = true;
    expect(() => decodeRun(run)).toThrow(ContractError);
    run.signal!.officialFacts = []; run.signal!.hypotheses = []; run.signal!.relationships = [];
    expect(decodeRun(run)).toEqual(run);
    run.signal!.sources[0].modelVisibleChars = 999;
    expect(() => decodeRun(run)).toThrow(ContractError);
    run.signal!.sources[0].modelVisibleChars = 2;
    run.signal!.discovery.candidates[0].url = 'https://leaf.example.test/news?token=secret';
    expect(() => decodeRun(run)).toThrow(ContractError);
  });
  it('requires v2 dataset/source data categories without silently defaulting', () => {
    const bootstrap = structuredClone(fictionalBootstrapV2);
    delete bootstrap.catalog.datasets[0].dataMode;
    expect(() => decodeBootstrap(bootstrap)).toThrow(ContractError);
  });
  it('preserves missing article and applicant names instead of inventing them', () => {
    const run = structuredClone(fictionalRunV2);
    run.signal!.recordFacts[0].articleName = null;
    run.signal!.recordFacts[0].applicant.name = null;
    run.input.context.entity.name = null;
    expect(decodeRun(run)).toEqual(run);
    const bootstrap = structuredClone(fictionalBootstrapV2);
    bootstrap.catalog.entities[0].name = null;
    expect(decodeBootstrap(bootstrap)).toEqual(bootstrap);
  });
});
