import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { fictionalRunV2 } from './fixtures';
import { SignalResult } from './SignalResult';
import { SignalStartGuide } from './SignalWorkspace';
import { ResultOverview } from './SignalContext';
import { SignalEmptyJourney, SignalPurposeIntro, SignalQuestionFocus, SignalQuestionPicker, SignalValuePreview } from './SignalPurposeJourney';
import { evidenceId } from './labels';

describe('first-time selection and evidence journey', () => {
  it('shows the audience, decision and a source-linked fictional example before asking for input', () => {
    const intro = renderToStaticMarkup(createElement(SignalPurposeIntro));
    expect(intro).toContain('競合のデザイン変化を');
    expect(intro).toContain('知財担当から企画・開発へ');
    expect(intro).toContain('次に必要な資料');
    const example = renderToStaticMarkup(createElement(SignalValuePreview));
    expect(example).toContain('架空の操作例 · 実AI未実施');
    expect(example).toContain('href="#signal-example-evidence"');
    expect(example).toContain('id="signal-example-evidence"');
    expect(example).toContain('円と長方形');
    expect(example).toContain('本社移転の引用は、図面の形状変更を裏付けません');
    expect(example).toContain('発表日は不明');
    expect(example).toContain('保存履歴には入りません');
    expect(example).not.toContain('href="https:');
    expect(example).not.toContain('/api/');
  });
  it('makes the selected question a viewing guide with a direct saved-evidence target', () => {
    const picker = renderToStaticMarkup(createElement(SignalQuestionPicker, { selected: 'support', disabled: false, onSelect: () => undefined }));
    expect(picker).toContain('公式の説明は図面を裏付ける？');
    expect(picker).toContain('aria-pressed="true"');
    expect(picker).toContain('この選択だけでは分析は始まりません');
    expect(picker).toContain('問いを指定した実AI分析は、まだ利用できません');
    expect(picker).toContain('分析入力として保存されません');
    const focus = renderToStaticMarkup(createElement(SignalQuestionFocus, { question: 'support' }));
    expect(focus).toContain('href="#signal-official"');
    expect(focus).toContain('分析し直したりはしません');
    expect(focus).toContain('この結果の実行入力や、保存された問いではありません');
    const next = renderToStaticMarkup(createElement(SignalQuestionFocus, { question: 'next' }));
    expect(next).toContain('href="#signal-next-checks"');
    const empty = renderToStaticMarkup(createElement(SignalEmptyJourney, { developmentMode: true }));
    expect(empty).toContain('実AIは実行しません');
    expect(empty).toContain('href="#signal-conditions"');
    const facts = renderToStaticMarkup(createElement(SignalEmptyJourney, { factsOnly: true }));
    expect(facts).toContain('図面・記事本文の分析は未実施');
    expect(facts).not.toContain('図面を見比べ');
    const pending = renderToStaticMarkup(createElement(SignalQuestionFocus, { question: 'drawings', hasEvidence: false }));
    expect(pending).toContain('根拠はまだ保存されていません');
    expect(pending).not.toContain('href=');
  });
  it('summarizes the exact saved observation and quotation without rewriting the run', () => {
    const run = structuredClone(fictionalRunV2);
    const saved = JSON.stringify(run);
    const html = renderToStaticMarkup(createElement(ResultOverview, { run }));
    expect(html).toContain(run.signal!.visualObservations[0].observation);
    expect(html).toContain(run.signal!.officialFacts[0].quote);
    expect(html).toContain(`href="#${evidenceId(run.signal!.officialFacts[0].id)}"`);
    expect(html).toContain(`href="#${evidenceId(run.signal!.visualObservations[0].id)}"`);
    expect(html).toContain('この観察と図面をここで確かめる');
    expect(html).toContain('この記載の引用・出典をここで確かめる');
    const result = renderToStaticMarkup(createElement(SignalResult, { run }));
    expect(result).toContain('href="#signal-images"');
    expect(result).toContain('実行時点の資料と分析状態');
    expect(result).toContain(run.createdAt);
    expect(result).toContain('実行時の問い：未記録');
    expect(result).not.toContain('閲覧する問い：');
    const demo = renderToStaticMarkup(createElement(ResultOverview, { run, developmentMode: true }));
    expect(demo).toContain('架空図面の固定の観察例');
    expect(demo).toContain('架空資料の固定の引用例');
    expect(JSON.stringify(run)).toBe(saved);
  });
  it('explains explicit start, saved-result reuse and passive viewing without implying automatic AI execution', () => {
    const html = renderToStaticMarkup(createElement(SignalStartGuide, { analysisMode: 'standard' }));
    expect(html).toContain('条件・比較A/Bの資料を選ぶ');
    expect(html).toContain('保存済みの同条件の結果がなければ');
    expect(html).toContain('選択・履歴閲覧・再読み込みだけでは開始しません');
    expect(html).toContain('id="signal-start-explanation"');
    const facts = renderToStaticMarkup(createElement(SignalStartGuide, { analysisMode: 'facts_only' }));
    expect(facts).toContain('画像・記事取得やAI呼出は行いません');
    const demo = renderToStaticMarkup(createElement(SignalStartGuide, { analysisMode: 'standard', developmentMode: true }));
    expect(demo).toContain('架空の比較例');
    expect(demo).toContain('このブラウザーに保存');
    expect(demo).toContain('実AIの実行や課金はありません');
    expect(demo).not.toContain('AI分析を含む新しい処理');
  });
  it('shows the exact saved next question near the overview and provides passive links back to selection and support/opposition', () => {
    const run = structuredClone(fictionalRunV2);
    const saved = JSON.stringify(run);
    const html = renderToStaticMarkup(createElement(SignalResult, { run }));
    expect(html).toContain('href="#signal-conditions"');
    expect(html).toContain('href="#signal-hypotheses"');
    expect(html).toContain('id="signal-hypotheses"');
    expect(html.indexOf('次に確認すること')).toBeLessThan(html.indexOf('id="signal-images"'));
    expect(html).toContain(run.signal!.questionsForHuman[0]);
    expect(html).toContain('確認事項と不足情報をすべて見る');
    expect(JSON.stringify(run)).toBe(saved);
  });
  it('keeps fictional source URLs as text in the local development view', () => {
    const html = renderToStaticMarkup(createElement(SignalResult, { run: fictionalRunV2, developmentMode: true }));
    expect(html).not.toContain('href="https:');
    expect(html).toContain('架空の参照先です');
    expect(html).toContain('架空の保存抜粋（実AIは未実施）');
    expect(html).toContain('架空図面の模擬観察（実AIは未実施）');
    expect(html).toContain('架空資料の記載・固定の引用例');
    expect(html).not.toContain('画像からのAI観察候補');
    expect(html).not.toContain('図面からのAI観察候補');
    expect(html).not.toContain('企業が公表した内容です');
    expect(html).toContain('自作の架空図面と固定の模擬観察を確かめる表示');
    expect(html).not.toContain('形状比較とAI観察候補の内容を確かめるため');
  });
});
